### ISSUE TITLE
'PAM-CLUSTER' should not be an option in the 'Select size' dropdown

### ISSUE THREAD

**Issue by StefanoDePascale** [AntheSevenants/NephoVis#70]
'PAM-CLUSTER' should not be an option in the 'Select size' dropdown, because it's a categorical variable, not a continuous one. It can just be removed from that menu. In the 'Select color' and 'Select shape' menus the same information is already available under the label 'MEDOID'.

**Comment by AntheSevenants** [comment]
This is beyond the application's control. Since the information is encoded as a number, it is processed as a number. To solve this issue, the **dataset** should be changed to encode the information categorically (e.g. "cluster-1", "cluster-2" ...), or the column should be removed.

It is undesirable to hardcode specific properties which should not be shown.

@montesmariana, any thoughts?

**Comment by montesmariana** [comment]
Yup, I agree with @AntheSevenants, that's a matter of the dataset, not something to be solved by the application.

**Comment by StefanoDePascale** [comment]
I didn't know whether the application was in some way able to recognize the format of the information in the dataset, or not.
