### ISSUE TITLE
Character encoding of concordances

### ISSUE THREAD

**Issue by StefanoDePascale** [AntheSevenants/NephoVis#71]
Is it possible to have UTF-8 encoding of the concordances of the tokens? Accented characters are now rendered with a question mark, for instance. Or should that be set at the level of the files?

**Comment by AntheSevenants** [comment]
I have noticed this is as well, but this is again beyond the scope of the application.

The dataset itself includes these characters as such. There is thus an issue in the data processing pipeline, or with the source corpus. NephoVis cannot "fix" the encoding errors, since the data is simply lost (as far as I can tell).
