### ISSUE TITLE
Lower transparency of dots

### ISSUE THREAD

**Issue by montesmariana** [AntheSevenants/NephoVis#74]
When not selected, the dots should not have full opacity; there are many dots, and we need some transparency to identify areas of overlap, mixed colors, etc.
This is why in the original code, dots only have full opacity when they are selected (and everything else has much higher transparency), and when no dots are selected all of them have opacity 0.7.

This is related to the colors. The current color palette will be very hard to see with a lower opacity. That is why the chosen color palette was the OkabeIto, which is defined here as `Constants.colourPalette` but only selected when there are more than 8 values (I'm making another issue for that).

**Comment by AntheSevenants** [comment]
This is a conscious decision. The opacity is disabled because the performance when brushing is absolutely atrocious with opacity enabled. I think this is simply just commented out at this point though, so I can restore it easily.

**Comment by montesmariana** [comment]
But the brushing is part of the selection process, right? During brushing it's ok, the selected tokens should have full opacity, but when no brushing is in place, in the "default" mode of having nothing selected, we need a lower opacity. Is that still messing with the brush?

**Comment by AntheSevenants** [comment]
Sorry, I misremembered. Opacity is disabled because you get a lot of framedrops when switching solutions:

Without opacity:

https://user-images.githubusercontent.com/84721952/161963455-7a677442-0fad-422d-809a-a625585f5948.mp4



With opacity:

https://user-images.githubusercontent.com/84721952/161963461-123b3e06-55e6-45f3-86ef-e848309d2230.mp4



However, opacity is only disabled for the aggregate level. All other levels are programmed to behave as you describe, and opacity _is_ thus enabled:
https://github.com/AntheSevenants/NephoVis/blob/3f5730730cd36db31ea4a1508984dfd7c4e59f15/src/Plot.js#L385-L391

Still, for the aggregate level, non-selected tokens should still be identifiable, since they also get the `.lighter` CSS class.

Does it have to do with the colour palette (https://github.com/AntheSevenants/NephoVis/issues/75) then?

**Comment by montesmariana** [comment]
Ahhh ok! Well, if I had to choose between keeping the lower opacity and keeping the animation when switching solutions (or keeping it smooth) I would prioritize the lower the opacity.
The lower opacity is _necessary_ in order to understand the overlap of points when you don't have selected parts, especially (but not only) after color coding. This can't be substituted by selecting some tokens and inspecting the non-selected, lighter tokens. And it has to be kept at level 2 as well, I personally do most of my analysis on level 2.
The (smooth) animation is more of an aesthetic thing instead.

**Comment by AntheSevenants** [comment]
A friend of mine tipped off the [fill-opacity](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/fill-opacity) property for SVG elements. It should have higher performance, so I'll have to test that first. Maybe that'll give us the best of both worlds? I'll try it out.

**Comment by AntheSevenants** [comment]
@montesmariana `fill-opacity` works much better! The only downside is that the point borders ("stroke") are not opaque (it is *fill* opacity after all). Do you mind?

https://user-images.githubusercontent.com/84721952/163217344-3cdc1a3f-9821-4fd6-9b43-7739679ec180.mp4

**Comment by AntheSevenants** [comment]
(implemented in https://github.com/AntheSevenants/NephoVis/commit/ec11fff54cde257480a6fc0c967aef901613a5fa for now)

**Comment by AntheSevenants** [comment]
Great!
