### ISSUE TITLE
Reinstate OkabeIto Palette

### ISSUE THREAD

**Issue by montesmariana** [AntheSevenants/NephoVis#75]
The chosen palette of the original NephoVis (based on Okabe & Ito's) is recorded as `Constants.colourPalette` but only selected when there are more than 8 values. This is pointless, since the palette only has 8 values.

To a certain degree, the choice of palette is a matter of style and taste, but I find that the current palette does not have enough of a contrast for the kind of analysis we need to do, and it will be worse with lower opacity.

**Comment by AntheSevenants** [comment]
I think I switched this because the legend's colour palette and the data point colour palette got mixed up for some reason. I do agree that the original one looks better. I'll look into it.

**Comment by AntheSevenants** [comment]
This behaviour was actually a bug. I only set the colour palette upon creation of a data style, but the colour palette should actually change depending on how many different possible values are currently assigned to that style. <8 = NephoVis style, >8 = d3 default.

The default colour palette is now properly set, and it also changes dynamically (like in the original implementation).

Fixed in https://github.com/AntheSevenants/NephoVis/commit/af9122a5d7b9f1732495b374c1a2fe4ae64ad7b7.
