### ISSUE TITLE
Shape legend breaks with "too many values"

### ISSUE THREAD

**Issue by montesmariana** [AntheSevenants/NephoVis#79]
**Scenario 1**
If there are few values in a categorical variable chosen to code the shapes of the dots in level 2, the legend works well.
When the variable has too many values, the shapes shown in the legend do not correspond to the shapes shown in the plot anymore, although clicking on the legend selects the appropriate tokens.
If, after this, we go back to a variable with few values, that legend breaks as well.

**Scenario 2**
If you select to code for shape, and then you select a different variable to code for shape, the legend breaks in the second case regardless of the number of values.

The video below illustrates the first scenario. Note that the variables with "too many values" have so many values that the shapes are recycled: this should not happen. Such a variable should not be available for shape coding to begin with.
But in another dataset (see picture below) this issue occurs even with a variable with a reasonable 6 values. (Notably, it happened if I had already used shape coding with another variable first, but not if it was the first variable?)

https://user-images.githubusercontent.com/54317904/162012129-70016232-a327-46c8-b2ae-7d61e419a783.mp4

![image](https://user-images.githubusercontent.com/54317904/162012222-2944f848-f192-4f48-9073-0d00bda1c3f2.png)

**Comment by AntheSevenants** [comment]
Scenarios 1 and 2 are related to each other. Because I recycled the d3 schema for each style, it just assumed that certain shapes had already been used, and assigned different ones. I now create a new d3 schema for every new variable/value assignment, so that problem is fixed so far in https://github.com/AntheSevenants/NephoVis/commit/1b50436360f0f1d6accb17b20c0c2fde4ef02c3f. Great find!

**Comment by AntheSevenants** [comment]
The repeating shapes also happen in the original implementation:
![image](https://user-images.githubusercontent.com/84721952/163256748-67a9653d-9855-4fd3-bdf8-5ad01a0c37c4.png)

How come?

https://github.com/AntheSevenants/NephoVis/blob/1b50436360f0f1d6accb17b20c0c2fde4ef02c3f/src/DataProcessor.js#L37-L38

It's based on nominalNames, which has an upper limit of 10 unique values, rather than 7 (which is the number of unique symbols d3 offers by default).

Possible solutions:

1. Create another subset of nominalNames which is filtered with an upper limit of 7
2. Import MORE symbols!!! (https://github.com/YellowTugboat/d3-symbol-extra)

Any thoughts, @montesmariana?

**Comment by AntheSevenants** [comment]
Correction: in the original implementation, the issue is _not always_ there:
https://github.com/AntheSevenants/NephoVis/blob/1b50436360f0f1d6accb17b20c0c2fde4ef02c3f/src/level2.js#L166-L167

e.g. in level 2, there is further filtering. But it needn't be this way! (see solution 2 above)

**Comment by AntheSevenants** [comment]
The plot thickens! I do this as well, but only on level 3 for some reason:
https://github.com/AntheSevenants/NephoVis/blob/2a50eefcc02160796379759656251dcd21725d01/src/NephoVisNew.js#L63-L66

The choice still remains though: do we add more symbols, or do we keep the filtering?

**Comment by montesmariana** [comment]
Ohhh I hadn't noticed it in the original implementation! (I don't use shapes that much).
I wouldn't add more shapes, it's already hard enough to distinguish 7 different shapes, especially in plots where the categories don't take clearly distinct areas...

**Comment by AntheSevenants** [comment]
Upper limit implemented for all levels in https://github.com/AntheSevenants/NephoVis/commit/24ada1c9a4e237ffb2bcbb6e3a30ed29205f2197.
